/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSpacer: typeof import('./src/components/AppSpacer.vue')['default']
    BladeApp: typeof import('./src/components/blade/BladeApp.vue')['default']
    BladeBattery: typeof import('./src/components/blade/BladeBattery.vue')['default']
    BladeClock: typeof import('./src/components/blade/BladeClock.vue')['default']
    BladeHassBadges: typeof import('./src/components/blade/hass/BladeHassBadges.vue')['default']
    BladeHosts: typeof import('./src/components/blade/BladeHosts.vue')['default']
    BladeMe: typeof import('./src/components/blade/BladeMe.vue')['default']
    BladeNowPlaying: typeof import('./src/components/blade/BladeNowPlaying.vue')['default']
    TemplateMain: typeof import('./src/components/toolbar/template/TemplateMain.vue')['default']
    TemplateSecondary: typeof import('./src/components/toolbar/template/TemplateSecondary.vue')['default']
    TheToolbar: typeof import('./src/components/TheToolbar.vue')['default']
    ToolbarItem: typeof import('./src/components/toolbar/item/ToolbarItem.vue')['default']
    ToolbarItemGroup: typeof import('./src/components/ToolbarItemGroup.vue')['default']
    ToolbarItemHoverGroup: typeof import('./src/components/toolbar/item/ToolbarItemHoverGroup.vue')['default']
    ToolbarTemplate: typeof import('./src/components/toolbar/template/ToolbarTemplate.vue')['default']
    ToolbarTemplateDouble: typeof import('./src/components/toolbar/template/ToolbarTemplateDouble.vue')['default']
    ToolbarTemplateFill: typeof import('./src/components/toolbar/template/ToolbarTemplateFill.vue')['default']
    ToolbarTemplateMain: typeof import('./src/components/toolbar/template/ToolbarTemplateMain.vue')['default']
    ToolbarTemplateSecondary: typeof import('./src/components/toolbar/template/ToolbarTemplateSecondary.vue')['default']
  }
}
